version: "3.5"
services:
    app:
        container_name: blockchain_hash_storage
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/usr/src/hash-storage
        ports:
            - "5000:5000"
        expose:
            - "5000"
